import os
# MYSQL.CONNECTOR Config
MYSQL_HOST = os.getenv("HOST")
MYSQL_USERNAME = os.getenv("USERNAME")
MYSQL_PASSWORD = os.getenv("PASSWORD")
MYSQL_PORT = 3306
MYSQL_DB_NAME = os.getenv("DB_NAME")

# APP_SECRETKEY
SECRET_KEY = os.getenv("SEC_KEY")
